controller_names:
  - xarm_trajectory_position_controller
  - xarm_gripper_trajectory_position_controller

xarm_trajectory_position_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
      - xarm_7_joint
      - xarm_2_joint
      - xarm_3_joint
      - xarm_4_joint
      - xarm_5_joint
      - xarm_6_joint

xarm_gripper_trajectory_position_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
      - xarm_1_joint
  #    - xarm_1_joint_mirror

#xarm_gripper_position_controller:
#   action_ns: gripper_action
#   type: GripperCommand
#   default: true
#   parallel: true
#   joints:
#      - xarm_1_joint
#      - xarm_1_joint_mirror
