publisher_forward_position_controller:
  ros__parameters:

    controller_name: "xarm_forward_position_controller"
    wait_sec_between_publish: 2

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    #pos1: [0, 0, 0, 0, 0]
    #pos2: [-0.5, 0.0, 0.0, 0.0, 0.0]
    #pos3: [0, 0, 0, 0, 0]
    #pos4: [0.5, 0.0, 0.0, 0.0, 0.0]

    #pos1: [0, 0, 0, 0, 0]
    #pos2: [0.0, 0.0, 0.0, 0.0, -1.59]
    #pos3: [0, 0, 0, 0, 0]
    #pos4: [0.0, 0.0, 0.0, 0.0, 1.86]

    pos1: [0.785, 0.785, 0.785, 0.5, 0.5]
    pos2: [0, 0, 0, 0, 0]
    pos3: [-0.785, -0.785, -0.785, -0.5, -0.5]
    pos4: [0, 0, 0, 0, 0]
