publisher_forward_position_controller:
  ros__parameters:

    controller_name: "xarm_gripper_forward_position_controller"
    wait_sec_between_publish: 2

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.028, -0.028]
    pos2: [0.003, -0.003]
    pos3: [0.028, -0.028]
    pos4: [0.003, -0.0035]
    pos4: [0.01, -0.01]

