controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"

    xarm_forward_position_controller:
      type: "forward_command_controller/ForwardCommandController"

    xarm_gripper_forward_position_controller:
      type: "forward_command_controller/ForwardCommandController"

    xarm_trajectory_position_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

    xarm_gripper_trajectory_position_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

xarm_forward_position_controller:
  ros__parameters:
    joints:
      - xarm_7_joint
      - xarm_2_joint
      - xarm_3_joint
      - xarm_4_joint
      - xarm_5_joint
      - xarm_6_joint

    interface_name: position

xarm_gripper_forward_position_controller:
  ros__parameters:
    joints:
      - xarm_1_joint
      - xarm_1_joint_mirror

    interface_name: position

xarm_trajectory_position_controller:
  ros__parameters:
    joints:
      - xarm_7_joint
      - xarm_2_joint
      - xarm_3_joint
      - xarm_4_joint
      - xarm_5_joint
      - xarm_6_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate:  100.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

xarm_gripper_trajectory_position_controller:
  ros__parameters:
    joints:
      - xarm_1_joint
    #  - xarm_1_joint_mirror

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate:  100.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
